// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package types

// Int32Stack is linear data structure
type Int32Stack struct {
	items []int32
}

func NewInt32Stack() *Int32Stack {
	return &Int32Stack{items: make([]int32, 0)}
}
func (q *Int32Stack) Push(item int32) {
	q.items = append(q.items, item)
}
func (q *Int32Stack) Pop() int32 {
	item := q.items[0]
	q.items = q.items[1:]
	return item
}
